<!DOCTYPE html>
<html lang="fr">
        <head>
            <meta charset="UTF-8">
            <title>Page d'accueil</title>
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <meta name="description" content="La rose ecarlate est un magasin de ventes de fleurs en ligne.">
            <meta name="keywords" content="Ventes de fleurs">
            <link rel="stylesheet" href="assets/css/style.css"><!--Here I have my link to my css-->
        </head>
    <body>
        <header class="header">
            <h1 class="title-big">Rose écarlate</h1>
            <h3>Offrir & décorer</h3>
                <nav class="header_nav">
                    <label for="btn" class="icon"><!--Here we have our burger-->
                        <svg viewbox="0 0 100 80" width="40" height="40">
                            <rect width="100" height="15"></rect>
                            <rect y="35" width="100" height="15"></rect>
                            <rect y="70" width="100" height="15"></rect>
                        </svg>
                    </label>
                    <input type="checkbox" id="btn">
                    <ul class="nav_menu"><!--Here I have my nav_menu-->
                        <li class="nav_item">
                            <a href="vue/boutique.php">Boutique</a>
                        </li>
                        <li class="nav_item">
                            <a href="vue/equipe.php"> L'équipe</a>
                        </li>
                        <li class="nav_item">
                            <a href="vue/contact.php">Nous contacter</a>
                        </li> 
                        <li class="nav_item">
                            <a href="vue/form_inscription_client.php">S'inscrire</a>
                        </li>
                        <li class="nav_item">
                            <a href="vue/connexion_admin.php">Se connecter</a> 
                        </li>
                    </ul>
                </nav> 
        </header>
        <main class="main"><!-- In my main I have articles from this weeks selection or our best sells, but this is not yet generated by PHP via my data base.-->
            <h2>"La sélection de la semaine"</h2>
            <div id="conteneur">
                <div class="element 1"><a href="produits/aricle1.html" target="_blank">
                <img src="assets/images/upload/bouquet_1.jpg"alt="" width="200" height="200">
                </a></div>

                <div class="element 2"><a href="produits/article3.html" target="_blank">
                <img src="assets/images/upload/bouquet_2.jpg"alt="" width="200" height="200">
                </a></div>

                <div class="element 3"><a href="produits/article7.html" target="_blank">
                <img src="assets/images/upload/bouquet_3.jpg"alt="" width="200" height="200">
                </a></div>
            </div>
            <h2>"Nos meilleurs ventes"</h2>
            <div id="conteneur_b">
                <div class="element 4"><a href="produits/article2.html" target="_blank">    
                <img src="assets/images/upload/bouquet_4.jpg" alt="" width="200" height="200">
                  
                </a></div>

                <div class="element 5"><a href="produits/article4.html" target="_blank">  
                <img src="assets/images/upload/bouquet_5.jpg" alt="" width="200" height="200">
                   
                </a></div>

                <div class="element 6"><a href="produits/article6.html" target="_blank">
                <img src="assets/images/upload/bouquet_6.jpg" alt="" width="200" height="200">
                    
                </a></div>
            </div>
                <!--<h2>Notre "Blog"</h2>
                <a href="blog.html" target="_blank">
                <img src="images/romantique.jpg" alt="Image romantique" width="200" height="150">
                Comment dire "je t'aime" avec des fleurs.
                </a>
                
                    <a href="blog.html" target="_blank">
                <img src="images/fleursambiance.jpg" alt="Déco d'interieur" width="200" height="150">
                Nouvelle année, nouvelle ambiance interieur.
                </a>-->
        </main>
        <footer class="footer">
            <p>Copyrights 2022</p>
        </footer>
    </body>
</html>