<?php
require_once "../entity/User.php";
session_start();
if(isset($_SESSION['user'])){
   

    $user=$_SESSION['user'];
    echo $user->getNom(); 
    $connected=true;
}else{
    $user=new User();
    $connected=false;

}
$page="accueil";

?>

<!DOCTYPE html>
<html lang="fr">
        <head>
            <meta charset="UTF-8">
            <title>Page d'accueil</title>
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <meta name="description" content="La rose ecarlate est un magasin de ventes de fleurs en ligne.">
            <meta name="keywords" content="Ventes de fleurs">
<link rel="stylesheet" href="../assets/css/bootstrap.min.css">
            <link rel="stylesheet" href="../assets/css/style.css"><!--Here I have my link to my css-->
        </head>
    <body>
        <header class="header">
            <h1 class="title-big">Rose écarlate</h1>
            <h3>Offrir & décorer</h3>
           <?php include_once "../vue/navigation.php";   ?>  
        </header>
        <div class="main"><!-- In my main I have articles from this weeks selection or our best sells, but this is not yet generated by PHP via my data base.-->
        <!--<div class="container">-->
        <?php  
            require_once "../model/produit.php";
        foreach(getProduitPublish_accueil() as $produit){
//Here I do a request to my data base without doing a prepare because it isn't gonna change it is solid.(She display all the questions given) 
        ?>    
            <div class="item <?=$produit->getProduit_id()?>">
                <a href="article.php?produit_id=<?=$produit->getProduit_id()?>" target="_blank">
                <img src="../controleur/export_image.php?image_id=<?=$produit->getImage_id()?>" alt="<?=$produit->getProduit_description()?>" width="200" height="200">
                </a>
            </div>
                <div class="item"><h2>"<?=$produit->getProduit_nom()?>"</h2>
                <span><?=$produit->getProduit_description()?></span>
                <h2><?=$produit->getProduit_prix()?>.00€</h2>
            </div>
       
                <?php
        }?>
        <!--</div>-->
        </div>
        
        <?php include_once"../vue/footer.php";?>
    </body>
</html>