<!DOCTYPE html>
<html lang="fr">
        <head>
            <meta charset="UTF-8">
            <title>Page d'accueil</title>
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <meta name="description" content="La rose ecarlate est un magasin de ventes de fleurs en ligne.">
            <meta name="keywords" content="Ventes de fleurs">

            <link rel="stylesheet" href="../assets/css/style.css"><!--Here I have my link to my css-->
        </head>
    <body>
        <header class="header">
            <h1 class="title-big">Rose écarlate</h1>
            <h3>Offrir & décorer</h3>
                <nav class="header_nav">
                    <label for="btn" class="icon"><!--Here we have our burger-->
                        <svg viewbox="0 0 100 80" width="40" height="40">
                            <rect width="100" height="15"></rect>
                            <rect y="35" width="100" height="15"></rect>
                            <rect y="70" width="100" height="15"></rect>
                        </svg>
                    </label>
                    <input type="checkbox" id="btn">
                    <ul class="nav_menu"><!--Here I have my nav_menu-->
                        <li class="nav_item">
                            <a href="boutique.php">Boutique</a>
                        </li>
                        <li class="nav_item">
                            <a href="equipe.php"> L'équipe</a>
                        </li>
                        <li class="nav_item">
                            <a href="contact.php">Nous contacter</a>
                        </li> 
                        <li class="nav_item">
                            <a href="form_inscription_client.php">S'inscrire</a>
                        </li>
                        <li class="nav_item">
                            <a href="connexion_admin.php">Se connecter</a> 
                        </li>
                    </ul>
                </nav> 
        </header>
        <main class="main"><!-- In my main I have articles from this weeks selection or our best sells, but this is not yet generated by PHP via my data base.-->
        <div id="conteneur" >
        <?php  
            require_once "../model/produit.php";
        foreach(getProduit() as $produit){
//Here I do a request to my data base without doing a prepare because it isn't gonna change it is solid.(She display all the questions given)
        ?>    
                <div class="element <?=$produit->getProduit_id()?>"><a href="article.php?produit_id=<?=$produit->getProduit_id()?>" target="_blank">
                <img src="../controleur/export_image.php?image_id=<?=$produit->getImage_id()?>" alt="<?=$produit->getProduit_description()?>" width="200" height="200">
              
                </a><h3><?=$produit->getProduit_nom()?></h3>
                <span><?=$produit->getProduit_prix()?></span>
            </div>


                <?php


        }?>
            </div>
                <!--<h2>Notre "Blog"</h2>
                <a href="blog.html" target="_blank">
                <img src="images/romantique.jpg" alt="Image romantique" width="200" height="150">
                Comment dire "je t'aime" avec des fleurs.
                </a>
                
                    <a href="blog.html" target="_blank">
                <img src="images/fleursambiance.jpg" alt="Déco d'interieur" width="200" height="150">
                Nouvelle année, nouvelle ambiance interieur.
                </a>-->
        </main>
        <footer class="footer">
            <p>Copyrights 2022</p>
        </footer>
    </body>
</html>