<?php
require_once "../entity/User.php";
session_start();
if(isset($_SESSION['user'])){
   

    $user=$_SESSION['user'];
    $connected=true;
}else{
    $user=new User();
    $connected=false;

}
$page="accueil";

?>

<!DOCTYPE html>
<html lang="fr">
        <head>
            <meta charset="UTF-8">
            <title>Page d'accueil</title>
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <meta name="description" content="La rose ecarlate est un magasin de ventes de fleurs en ligne.">
            <meta name="keywords" content="Ventes de fleurs">
            <link rel="stylesheet" href="../assets/css/bootstrap-5.1.3/dist/css/bootstrap.css">
            <link rel="stylesheet" href="../assets/css/style.css"><!--Here I have my link to my css-->
        </head>
    <body>
        <div class="container">
            <header class="py-3 d-flex flex-wrap align-items-center justify-content-center justify-content-md-between md-4 border-bottom">
                <a class="d-flex align-items-center col-md-3 mb-2 mb-md-0" href="/"><img width="" height="70" src="../assets/images/logo_fcomme_fleurs.jpg" alt=""></a>
                <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">

<li>
    <a class='nav-link px-2 link-<?= $page == 'accueil' ? "secondary" : "dark" ?>' href="accueil.php">Accueil</a>
</li>
<li>
    <a class='nav-link px-2 link-<?= $page == 'boutique' ? "secondary" : "dark" ?>' href="boutique.php">Boutique</a>
</li>
<li>
    <a class='nav-link px-2 link-<?= $page == 'equipe' ? "secondary" : "dark" ?>' href="equipe.php"> L'équipe</a>
</li>
<li>
    <a class='nav-link px-2 link-<?= $page == 'contact' ? "secondary" : "dark" ?>' href="contact.php">Nous contacter</a>
</li>
</ul>
<div class="col-md-3 text-end"><button class='btn btn-outline-primary me-2'>Login</button><button class='btn btn-primary'>Sign-up</button></div>

            </header>
        <main>
        <div class="container py-3"><!-- In my main I have articles from this weeks selection or our best sells, but this is not yet generated by PHP via my data base.-->
        <!--<div class="container">-->
            <div class="row row-cols-1 row-cols-sm-2 g-3" >
        <?php  
            require_once "../model/produit.php";
        foreach(getProduitPublish_accueil() as $produit){
//Here I do a request to my data base without doing a prepare because it isn't gonna change it is solid.(She display all the questions given) 
        ?>    
            <div class="col  <?=$produit->getProduit_id()?>">
            <div class="card shadow-sm">
                <div class="row">
                <div class="col-auto">
               <a href="article.php?produit_id=<?=$produit->getProduit_id()?>" target="_blank">
                <img src="../controleur/export_image.php?image_id=<?=$produit->getImage_id()?>" alt="<?=$produit->getProduit_description()?>" width="225" height="225">
                </a></div>
                <div class="col p-4">
                    
                <h2>"<?=$produit->getProduit_nom()?>"</h2>
                <p><?=substr($produit->getProduit_description(),0,100)."..."?></p>
               <div class="d-flex justify-content-between align-items-center">
                <h4 class="gy-2"><?=$produit->getProduit_prix()?>.00€</h4>
                </div>
                </div> 
                </div>   
            </div>
            </div>
            
                <?php
        }?>
        </div>
        <!--</div>-->
        </div>
        </main>
        <?php include_once"../vue/footer.php";?>
    </body>
</html>